secrets_file: null
openai_config: null

env:
  HF_HOME: null
  TRANSFORMERS_CACHE: null
  CUDA_VISIBLE_DEVICES: null

eval_model: null

openai: null

dataset: null
category: null
tool_pretraining_data_path: null

model_name: null
run_tag: null

per_device_train_batch_size: null
num_train_epochs: null
learning_rate: null
max_seq_length: null
pad_to_multiple_of: null

file_log_every_n_steps: null
console_log_every_n_steps: null
log_level: null

lora_rank: null
lora_alpha: null
